version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11 
    commands:
      - echo Updating package lists...
      - apt-get update -y
      - echo Installing Maven...
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Preparing environment variables...
      - export DB_HOST=vp-rds-instance.c1u4si4autpe.us-east-1.rds.amazonaws.com
      - export DB_USERNAME=admin
      - export DB_PASSWORD=RdsDatabase123
      - export MEMCACHED_ACTIVE_HOST=cl-vp-1papznnvna9wq.9tytbr.cfg.use1.cache.amazonaws.com
      - export RABBITMQ_ADDRESS=b-445f5f54-01c1-489a-8802-d688387739cf-1.mq.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the project...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - target/*.jar
