version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11 
    commands:
      - echo "📦 Updating package lists..."
      - sudo apt-get update -y
      - echo "🔧 Installing required packages..."
      - sudo apt-get install -y maven mysql-client

  pre_build:
    commands:
      - echo "🔍 Setting up environment variables..."
      - export DB_HOST=$(aws ssm get-parameter --name "/vprofile/db_host" --query "Parameter.Value" --output text)
      - export DB_USERNAME=$(aws ssm get-parameter --name "/vprofile/db_user" --with-decryption --query "Parameter.Value" --output text)
      - export DB_PASSWORD=$(aws ssm get-parameter --name "/vprofile/db_password" --with-decryption --query "Parameter.Value" --output text)

  build:
    commands:
      - echo "🔎 Checking environment variables..."
      - echo "DB_HOST: $DB_HOST"
      - echo "DB_USERNAME: $DB_USERNAME"
      - echo "DB_PASSWORD: (hidden)"

      - echo "🔎 Checking if db_backup.sql exists..."
      - if [ ! -f db_backup.sql ]; then echo "❌ Error: db_backup.sql not found!"; exit 1; fi

      - echo "🔎 Testing MySQL connection..."
      - mysqladmin -h $DB_HOST -u $DB_USERNAME -p$DB_PASSWORD ping

      - echo "🚀 Importing database backup..."
      - export MYSQL_PWD=$DB_PASSWORD
      - mysql -h $DB_HOST -u $DB_USERNAME accounts < db_backup.sql

  post_build:
    commands:
      - echo "✅ Database import completed successfully."

artifacts:
  files:
    - db_backup.sql
